const GET_ERRORS = 'GET_ERRORS';

export const LAYOUT = {
    SET_DEFAULT_FILTERS: 'SET_DEFAULT_FILTERS',
    TOGGLE_NAV: 'TOGGLE_NAV',
    TOGGLE_SUB_MENU: 'TOGGLE_SUB_MENU',
}

export const CHARACTER = {
    GET_ALL: 'GET_CHARACTERS',
    GET_ONE: 'GET_ONE_CHARACTER',
    SET_FAV: 'SET_FAB_CHAR',
    SET_FILTER: 'SET_CHAR_FILTER',
    ON_SEARCH: 'ON_SEARCH',
    SET_ERROR: GET_ERRORS
}

export const COMIC = {
    GET_ALL: 'GET_COMICS',
    GET_ONE: 'GET_ONE_COMIC',
    SET_FILTER: 'SET_COMIC_FILTER',
    SET_ERROR: GET_ERRORS
}

export const STORY = {
    GET_ALL: 'GET_STORIES',
    GET_ONE: 'GET_ONE_STORY',
    SET_ERROR: GET_ERRORS
}


